

<?php
/**
 * Implements hook_theme().
 */
// function scfp_landing_page_theme($existing, $type, $theme, $path) {
  // return [
  //   'scfphomepage' => [
  //       'variables' => ['version' => NULL],

  //   ],
  // ];
// }


/**
 * Implementing hook_theme().
 */
// function scfp_landing_page_theme($existing, $type, $theme, $path) {

  // return array(

  //   'article_list' => array(
      
  //     'variables' => array('items' => array(), 'title' => '')
  //   )
  // );
// }