<?php

/**
 * @file
 * Field Collection to Paragraphs module functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_collection_to_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the field_collection_to_paragraphs module.
    case 'help.page.field_collection_to_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration for Field Collections to Paragraphs.') . '</p>';
      return $output;
  }

  return NULL;
}
